services:
    app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html
            PROJECT_ENVIRONMENT: development

        user: 1000:1000
